<h1 
  id = "title"; 
  style="color:#4974a5; border-bottom: 3px solid #4974a5;"
>
  Analyzing Crime in LA

</h1>  

<h3 
  id = "title"; 
  style="color:#207d06;  border-bottom: 3px solid #207d06;"
>

## üåáüöî¬†Background

</h3>
![Los Angeles skyline](la_skyline.jpg)

Los Angeles, California üòé. The City of Angels. Tinseltown. The Entertainment Capital of the World! Known for its warm weather, palm trees, sprawling coastline, and Hollywood, along with producing some of the most iconic films and songs!

However, as with any highly populated city, it isn't always glamorous and there can be a large volume of crime. That's where you can help!

You have been asked to support the Los Angeles Police Department (LAPD) by analyzing their crime data to identify patterns in criminal behavior. They plan to use your insights to allocate resources effectively to tackle various crimes in different areas.

You are free to use any methodologies that you like in order to produce your insights. 



<h2 
  id= "";
  style="color:#8fca6b; border-bottom: 1px solid #207d06;"
>
</h2>

<p 
  id = "by-jamie-dormaar"; 
  style="
    font-family:JetBrains Mono;
    letter-spacing: 1px;
    color:#8fca6b;
    font-size:110%;
    text-align:left;"
>
  DataCamp submission by Jamie Dormaar
</p>

## ‚úÖ Checklist before publishing


* Rename your workspace to make it descriptive of your work. N.B. you should leave the notebook name as notebook.ipynb.
* Remove redundant cells like the judging criteria, so the workbook is focused on your work.
* Check that all the cells run without error.

<h2 id= "TOC"; style="color:#207d06; text-align:left; padding: 0px; border-bottom: 3px solid #207d06;">TABLE OF CONTENTS</h2>


- [THE DATA](#the-data)
- [EXPLORATION](#exploration)
- [DATA CLEANING](#data-cleaning)
    - [DATA FORMAT CONSISTENCY](#data-format-consistency)
    - [MISSING VALUES](#missing-values)

<!--
- [PREPROCESS DATA](#preprocess-data)
- [DATA CLEANING](#revise-data-cleaning)
    - [TARGET VARIABLE REFINEMENT](#target-variable-refinement)
    - [MERGING DATA SOURCES](#merging-data-sources)
        - [CLASSIFICATION OF PROTEIN FAMILIES (P-FAM)](#pfam)
        - [KAGGLE DATASET: STRUCTURAL PROTEIN SEQUENCES (with protein crystallization and xray crystallography specifications)](#xray)
- [SELECTING A TARGET VARIABLE](#select-target-variable)
- [FEATURE ENGINEERING](#feature-engineering)
    - [NLP REPRESENTATIONS](#nlp-representations)
        - [N-GRAMS](#n-grams)
    - [AMINO ACID PHYSICAL PROPERTIES](#aa-physical-properties)
        - [NET PROTEIN ACIDITY](#acidity)
        - [HYDROPATHY INDEX](#hydropathy-index)
        - [NET PROTEIN CHARGE](#net_charge)
- [MODELING](#modeling)
    - [SPLITTING DATA](#splitting-data)
    - [MODEL TRAINING](#model-training)
    - [MODEL EVALUATION](#model-evaluation)
    - [TUNE HYPERPARAMETERS](#tune-hyperparameters)
- [DEPLOYMENT](#deployment)
- [DISCUSSION](#discussion)
- [REFERENCES](#references)
    - [DATA SOURCES](#data-sources)
    - [TEXT REFERENCES](#text-references)
--->



<!--
Doc Headers:
<h4 id= ""; style="color:#c8d43e; text-align:left; padding: 0px; border-bottom: 1px solid #c8d43e;"></h4>
<h2 id= "the-data"; style="color:#207d06; text-align:left; padding: 0px; border-bottom: 3px solid #207d06;">THE DATA</h2>
<h2 id= "exploration"; style="color:#207d06; text-align:left; padding: 0px; border-bottom: 3px solid #207d06;">EXPLORATION</h2>
<h2 id= "data-cleaning"; style="color:#207d06; text-align:left; padding: 0px; border-bottom: 3px solid #207d06;">DATA CLEANING</h2>
<h3 id= "data-format-consistency"; style="color:#8fca6b; text-align:left; padding: 0px; border-bottom: 2px solid #8fca6b;">DATA FORMAT CONSISTENCY</h3>
<h3 id= "missing-values"; style="color:#8fca6b; text-align:left; padding: 0px; border-bottom: 2px solid #8fca6b;">MISSING VALUES</h3>


<h2 id= "preprocess-data"; style="color:#207d06; text-align:left; padding: 0px; border-bottom: 3px solid #207d06;">PREPROCESS DATA</h2>
<h3 id= "target-variable-refinement"; style="color:#8fca6b; text-align:left; padding: 0px; border-bottom: 2px solid #8fca6b;">TARGET VARIABLE REFINEMENT</h3>
<h3 id= "merging-data-sources"; style="color:#8fca6b; text-align:left; padding: 0px; border-bottom: 2px solid #8fca6b;">MERGING DATA SOURCES</h3>
<h4 id= "pfam"; style="color:#c8d43e; text-align:left; padding: 0px; border-bottom: 1px solid #c8d43e;">CLASSIFICATION OF PROTEIN FAMILIES (P-FAM)</h4>
<h4 id= "xray"; style="color:#c8d43e; text-align:left; padding: 0px; border-bottom: 1px solid #c8d43e;">KAGGLE DATASET: STRUCTURAL PROTEIN SEQUENCES (with protein crystallization and xray crystallography specifications)</h4>
<h3 id= "select-target-variable"; style="color:#8fca6b; text-align:left; padding: 0px; border-bottom: 2px solid #8fca6b;">SELECTING A TARGET VARIABLE</h3>
<h2 id= "feature-engineering"; style="color:#207d06; text-align:left; padding: 0px; border-bottom: 3px solid #207d06;">FEATURE ENGINEERING</h2>
<h3 id= "nlp-representations"; style="color:#8fca6b; text-align:left; padding: 0px; border-bottom: 2px solid #8fca6b;">NLP REPRESENTATIONS</h3>
<h4 id= "n-grams"; style="color:#c8d43e; text-align:left; padding: 0px; border-bottom: 1px solid #c8d43e;">N-GRAMS</h4>
<h4 id= "aa-physical-properties"; style="color:#c8d43e; text-align:left; padding: 0px; border-bottom: 1px solid #c8d43e;">AMINO ACID PHYSICAL PROPERTIES</h4>
<h5 id= "acidity"; style="color:#ff7400; text-align:left; padding: 0px; border-bottom: 1px solid #ff7400;">NET PROTEIN ACIDITY</h5>
<h5 id= "hydropathy-index"; style="color:#ff7400; text-align:left; padding: 0px; border-bottom: 1px solid #ff7400;">HYDROPATHY INDEX</h5>
<h5 id= "net_charge"; style="color:#ff7400; text-align:left; padding: 0px; border-bottom: 1px solid #ff7400;">NET PROTEIN CHARGE</h5>
<h2 id= "modeling"; style="color:#207d06; text-align:left; padding: 0px; border-bottom: 3px solid #207d06;">MODELING</h2>
<h3 id= "splitting-data"; style="color:#8fca6b; text-align:left; padding: 0px; border-bottom: 2px solid #8fca6b;">SPLITTING DATA</h3>
<h3 id= "model-training"; style="color:#8fca6b; text-align:left; padding: 0px; border-bottom: 2px solid #8fca6b;">MODEL TRAINING</h3>
<h3 id= "model-evaluation"; style="color:#8fca6b; text-align:left; padding: 0px; border-bottom: 2px solid #8fca6b;">MODEL EVALUATION</h3>
<h2 id= "tune-hyperparameters"; style="color:#207d06; text-align:left; padding: 0px; border-bottom: 3px solid #207d06;">TUNE HYPERPARAMETERS</h2>
<h2 id= "deployment"; style="color:#207d06; text-align:left; padding: 0px; border-bottom: 3px solid #207d06;">DEPLOYMENT</h2>
<h2 id= "discussion"; style="color:#207d06; text-align:left; padding: 0px; border-bottom: 3px solid #207d06;">DISCUSSION</h2>
<h2 id= "references"; style="color:#207d06; text-align:left; padding: 0px; border-bottom: 3px solid #207d06;">REFERENCES</h2>
<h3 id= "data-sources"; style="color:#8fca6b; text-align:left; padding: 0px; border-bottom: 2px solid #8fca6b;">DATA SOURCES</h3>
<h3 id= "academic-journal-publications"; style="color:#8fca6b; text-align:left; padding: 0px; border-bottom: 2px solid #8fca6b;">ACADEMIC JOURNAL PUBLICATIONS</h3>
<h3 id= "text-references"; style="color:#8fca6b; text-align:left; padding: 0px; border-bottom: 2px solid #8fca6b;">TEXT REFERENCES</h3>
<h3 id= "online-publications"; style="color:#8fca6b; text-align:left; padding: 0px; border-bottom: 2px solid #8fca6b;">ONLINE PUBLICATIONS</h3>
<h3 id= "footnotes"; style="color:#8fca6b; text-align:left; padding: 0px; border-bottom: 2px solid #8fca6b;">FOOTNOTES</h3>
-->

<h2 id= "the-data"; style="color:#207d06; text-align:left; padding: 0px; border-bottom: 3px solid #207d06;">THE DATA</h2>

# The Data

They have provided you with a single dataset to use. A summary and preview is provided below.

The data is publicly available [here](https://data.lacity.org/Public-Safety/Crime-Data-from-2020-to-Present/2nrs-mtv8).

## üëÆ‚Äç‚ôÄÔ∏è crimes.csv

| Column     | Description              |
|------------|--------------------------|
| `'DR_NO'` | Division of Records Number: Official file number made up of a 2 digit year, area ID, and 5 digits. |
| `'Date Rptd'` | Date reported - MM/DD/YYYY. |
| `'DATE OCC'` | Date of occurrence - MM/DD/YYYY. |
| `'TIME OCC'` | In 24 hour military time. |
| `'AREA'` | The LAPD has 21 Community Police Stations referred to as Geographic Areas within the department. These Geographic Areas are sequentially numbered from 1-21. |
| `'AREA NAME'` | The 21 Geographic Areas or Patrol Divisions are also given a name designation that references a landmark or the surrounding community that it is responsible for. For example 77th Street Division is located at the intersection of South Broadway and 77th Street, serving neighborhoods in South Los Angeles. |
| `'Rpt Dist No'` | A four-digit code that represents a sub-area within a Geographic Area. All crime records reference the "RD" that it occurred in for statistical comparisons. Find LAPD Reporting Districts on the LA City GeoHub at http://geohub.lacity.org/datasets/c4f83909b81d4786aa8ba8a74ab |
| `'Crm Cd'` | Crime code for the offense committed. |
| `'Crm Cd Desc'` | Definition of the crime. |
| `'Vict Age'` | Victim Age (years) |
| `'Vict Sex'` | Victim's sex: `F`: Female, `M`: Male, `X`: Unknown. |
| `'Vict Descent'` | Victim's descent:<ul><li>`A` - Other Asian</li><li>`B` - Black</li><li>`C` - Chinese</li><li>`D` - Cambodian</li><li>`F` - Filipino</li><li>`G` - Guamanian</li><li>`H` - Hispanic/Latin/Mexican</li><li>`I` - American Indian/Alaskan Native</li><li>`J` - Japanese</li><li>`K` - Korean</li><li>`L` - Laotian</li><li>`O` - Other</li><li>`P` - Pacific Islander</li><li>`S` - Samoan</li><li>`U` - Hawaiian</li><li>`V` - Vietnamese</li><li>`W` - White</li><li>`X` - Unknown</li><li>`Z` - Asian Indian</li> |
| `'Premis Cd'` | Code for the type of structure, vehicle, or location where the crime took place. |
| `'Premis Desc'` | Definition of the `'Premis Cd'`. |
| `'Weapon Used Cd'` | The type of weapon used in the crime. |
| `'Weapon Desc'` | Description of the weapon used (if applicable). |
| `'Status Desc'` | Crime status. |
| `'Crm Cd 1'` | Indicates the crime committed. Crime Code 1 is the primary and most serious one. Crime Code 2, 3, and 4 are respectively less serious offenses. Lower crime class numbers are more serious. |
| `'Crm Cd 2'` | May contain a code for an additional crime, less serious than Crime Code 1. |
| `'Crm Cd 3'` | May contain a code for an additional crime, less serious than Crime Code 1. |
| `'Crm Cd 4'` | May contain a code for an additional crime, less serious than Crime Code 1. |
| `'LOCATION'` | Street address of the crime. |
| `'Cross Street'` | Cross Street of rounded Address |
| `'LAT'` | Latitude of the crime location. |
| `'LON'` | Longitude of the crime location. |

In [230]:
import pandas as pd

In [231]:
crimes = pd.read_csv('data/crimes.csv')
crimes.head()

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Crm Cd,Crm Cd Desc,Vict Age,...,Weapon Desc,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,201223780,2020-11-02,11/02/2020 12:00:00 AM,1120,12,77th Street,1256,210,ROBBERY,65,...,FOLDING KNIFE,Invest Cont,210.0,NaN,NaN,NaN,73RD ST,FIGUEROA ST,33.9737,-118.2827
1,201911283,2020-06-23,06/23/2020 12:00:00 AM,315,19,Mission,1958,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",51,...,NaN,Invest Cont,740.0,998.0,NaN,NaN,9700 WOODMAN AV,NaN,34.2467,-118.4479
2,200806654,2020-02-28,02/28/2020 12:00:00 AM,1545,8,West LA,885,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),38,...,NaN,Invest Cont,420.0,NaN,NaN,NaN,10400 W PICO BL,NaN,34.0463,-118.4171
3,220912167,2022-08-03,07/26/2022 12:00:00 AM,1730,9,Van Nuys,955,901,VIOLATION OF RESTRAINING ORDER,64,...,NaN,Adult Other,901.0,NaN,NaN,NaN,14200 MAGNOLIA BL,NaN,34.1668,-118.4445
4,200817110,2020-12-02,11/27/2020 12:00:00 AM,1500,8,West LA,802,662,"BUNCO, GRAND THEFT",73,...,NaN,Invest Cont,662.0,NaN,NaN,NaN,15000 W SUNSET BL,NaN,34.0889,-118.5325

<h2 id= "exploration"; style="color:#207d06; text-align:left; padding: 0px; border-bottom: 3px solid #207d06;">EXPLORATION</h2>

In [232]:
crimes.shape

(400146, 25)

In [233]:
crimes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400146 entries, 0 to 400145
Data columns (total 25 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   DR_NO           400146 non-null  int64
 1   Date Rptd       400146 non-null  object
 2   DATE OCC        400146 non-null  object
 3   TIME OCC        400146 non-null  int64
 4   AREA            400146 non-null  int64
 5   AREA NAME       400146 non-null  object
 6   Rpt Dist No     400146 non-null  int64
 7   Crm Cd          400146 non-null  int64
 8   Crm Cd Desc     400146 non-null  object
 9   Vict Age        400146 non-null  int64
 10  Vict Sex        346271 non-null  object
 11  Vict Descent    346268 non-null  object
 12  Premis Cd       400140 non-null  float64
 13  Premis Desc     399910 non-null  object
 14  Weapon Used Cd  136027 non-null  float64
 15  Weapon Desc     136027 non-null  object
 16  Status Desc     400146 non-null  object
 17  Crm Cd 1        400140 non-null  float64
 18  Crm Cd 2        28121 non-null   float64
 19  Crm Cd 3        798 non-null     float64
 20  Crm Cd 4        0 non-null       float64
 21  LOCATION        400146 non-null  object
 22  Cross Street    64582 non-null   object
 23  LAT             400146 non-null  float64
 24  LON             400146 non-null  float64
dtypes: float64(8), int64(6), object(11)
memory usage: 76.3+ MB

In [234]:
# Save a working copy
df = crimes.copy()

<h2 id= "data-cleaning"; style="color:#207d06; text-align:left; padding: 0px; border-bottom: 3px solid #207d06;">DATA CLEANING</h2>

<h3 id= "data-format-consistency"; style="color:#8fca6b; text-align:left; padding: 0px; border-bottom: 2px solid #8fca6b;">DATA FORMAT CONSISTENCY</h3>

<h4 id= ""; style="color:#c8d43e; text-align:left; padding: 0px; border-bottom: 1px solid #c8d43e;">COLUMN HEADINGS</h4>

The column titles are currently a mix of upper and lower case. for consistency they will all be reformatted to snake case:

In [235]:
# create list of column titles
cols = crimes.columns.tolist()

# change the spaces to underscores
cols = [x.replace(' ', '_') for x in cols]

# convert all to lower case
cols = [x.lower() for x in cols]

# confirm results by printing a few,
cols[:4]

['dr_no', 'date_rptd', 'date_occ', 'time_occ']

In [236]:
# Create a dictionary keying the old headings to the new:
old_cols = df.columns.tolist()
col_map = dict(zip(old_cols, cols))

col_map

{'DR_NO': 'dr_no',
 'Date Rptd': 'date_rptd',
 'DATE OCC': 'date_occ',
 'TIME OCC': 'time_occ',
 'AREA': 'area',
 'AREA NAME': 'area_name',
 'Rpt Dist No': 'rpt_dist_no',
 'Crm Cd': 'crm_cd',
 'Crm Cd Desc': 'crm_cd_desc',
 'Vict Age': 'vict_age',
 'Vict Sex': 'vict_sex',
 'Vict Descent': 'vict_descent',
 'Premis Cd': 'premis_cd',
 'Premis Desc': 'premis_desc',
 'Weapon Used Cd': 'weapon_used_cd',
 'Weapon Desc': 'weapon_desc',
 'Status Desc': 'status_desc',
 'Crm Cd 1': 'crm_cd_1',
 'Crm Cd 2': 'crm_cd_2',
 'Crm Cd 3': 'crm_cd_3',
 'Crm Cd 4': 'crm_cd_4',
 'LOCATION': 'location',
 'Cross Street': 'cross_street',
 'LAT': 'lat',
 'LON': 'lon'}

In [237]:
# Rename the columns in the table.
df = df.rename(columns=col_map)
df.head()

,dr_no,date_rptd,date_occ,time_occ,area,area_name,rpt_dist_no,crm_cd,crm_cd_desc,vict_age,...,weapon_desc,status_desc,crm_cd_1,crm_cd_2,crm_cd_3,crm_cd_4,location,cross_street,lat,lon
0,201223780,2020-11-02,11/02/2020 12:00:00 AM,1120,12,77th Street,1256,210,ROBBERY,65,...,FOLDING KNIFE,Invest Cont,210.0,NaN,NaN,NaN,73RD ST,FIGUEROA ST,33.9737,-118.2827
1,201911283,2020-06-23,06/23/2020 12:00:00 AM,315,19,Mission,1958,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",51,...,NaN,Invest Cont,740.0,998.0,NaN,NaN,9700 WOODMAN AV,NaN,34.2467,-118.4479
2,200806654,2020-02-28,02/28/2020 12:00:00 AM,1545,8,West LA,885,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),38,...,NaN,Invest Cont,420.0,NaN,NaN,NaN,10400 W PICO BL,NaN,34.0463,-118.4171
3,220912167,2022-08-03,07/26/2022 12:00:00 AM,1730,9,Van Nuys,955,901,VIOLATION OF RESTRAINING ORDER,64,...,NaN,Adult Other,901.0,NaN,NaN,NaN,14200 MAGNOLIA BL,NaN,34.1668,-118.4445
4,200817110,2020-12-02,11/27/2020 12:00:00 AM,1500,8,West LA,802,662,"BUNCO, GRAND THEFT",73,...,NaN,Invest Cont,662.0,NaN,NaN,NaN,15000 W SUNSET BL,NaN,34.0889,-118.5325

<h4 id= ""; style="color:#c8d43e; text-align:left; padding: 0px; border-bottom: 1px solid #c8d43e;">TIME FORMAT</h4>

In [238]:
# Check on the date and time dtypes and formats:
df[['date_rptd', 'date_occ', 'time_occ']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400146 entries, 0 to 400145
Data columns (total 3 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   date_rptd  400146 non-null  object
 1   date_occ   400146 non-null  object
 2   time_occ   400146 non-null  int64
dtypes: int64(1), object(2)
memory usage: 9.2+ MB

In [239]:
df['time_occ'].head()

0    1120
1     315
2    1545
3    1730
4    1500
Name: time_occ, dtype: int64

Change the 24 hour time format from int64 for better chronological visualizations analyses later:

In [240]:
# Format time values with leading zeros, so the datetime function can understand them.
df['time_occ'] = df['time_occ'].apply(lambda x: f"{x:04d}")
df['time_occ'].head()

0    1120
1    0315
2    1545
3    1730
4    1500
Name: time_occ, dtype: object

In [241]:
# Convert time values to datetime objects
df['time_occ'] = df['time_occ'].apply(lambda x: pd.to_datetime(str(x), format='%H%M').time())
df['time_occ'].head()

0    11:20:00
1    03:15:00
2    15:45:00
3    17:30:00
4    15:00:00
Name: time_occ, dtype: object

In [242]:
df['time_occ'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 400146 entries, 0 to 400145
Series name: time_occ
Non-Null Count   Dtype
--------------   -----
400146 non-null  object
dtypes: object(1)
memory usage: 3.1+ MB

In [243]:
premis = df[df['premis_cd'].notna()]
prem_desc_nulls = premis[premis['premis_desc'].isna()][['premis_cd', 'premis_desc']].copy()

display(prem_desc_nulls['premis_cd'].value_counts())
display(prem_desc_nulls.shape)

prem_desc_nulls.head()

418.0    160
256.0     67
972.0      3
Name: premis_cd, dtype: int64

(230, 2)

      premis_cd premis_desc
2493      256.0         NaN
3658      418.0         NaN
5046      418.0         NaN
6505      418.0         NaN
6776      256.0         NaN

In [244]:
# df[['premis_cd', 'premis_desc']].groupby('')

In [245]:
x = df[df['premis_cd'] == (418.0 or 256.0 or 972.0)][['premis_cd', 'premis_desc']].copy()
x.isna().sum()

premis_cd        0
premis_desc    160
dtype: int64

In [246]:
df['weapon_desc'].value_counts()

STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)    70535
UNKNOWN WEAPON/OTHER WEAPON                       14667
VERBAL THREAT                                     10382
HAND GUN                                           8834
SEMI-AUTOMATIC PISTOL                              3243
                                                  ...
UZI SEMIAUTOMATIC ASSAULT RIFLE                       3
ANTIQUE FIREARM                                       3
MAC-11 SEMIAUTOMATIC ASSAULT WEAPON                   2
MAC-10 SEMIAUTOMATIC ASSAULT WEAPON                   2
M1-1 SEMIAUTOMATIC ASSAULT RIFLE                      1
Name: weapon_desc, Length: 77, dtype: int64

<h3 id= "missing-values"; style="color:#8fca6b; text-align:left; padding: 0px; border-bottom: 2px solid #8fca6b;">MISSING VALUES</h3>

In [247]:
# Quantize missing values:
df.isna().sum()

dr_no                  0
date_rptd              0
date_occ               0
time_occ               0
area                   0
area_name              0
rpt_dist_no            0
crm_cd                 0
crm_cd_desc            0
vict_age               0
vict_sex           53875
vict_descent       53878
premis_cd              6
premis_desc          236
weapon_used_cd    264119
weapon_desc       264119
status_desc            0
crm_cd_1               6
crm_cd_2          372025
crm_cd_3          399348
crm_cd_4          400146
location               0
cross_street      335564
lat                    0
lon                    0
dtype: int64

crm_cd_4 is a completely empty column, so there's no point in keeping it

In [248]:
df.drop(['crm_cd_4'], axis=1, inplace=True)

In [249]:
# Unique Values:
df.nunique()

dr_no             400146
date_rptd           1280
date_occ            1280
time_occ            1439
area                  21
area_name             21
rpt_dist_no         1171
crm_cd               112
crm_cd_desc          112
vict_age             102
vict_sex               4
vict_descent          20
premis_cd            305
premis_desc          302
weapon_used_cd        77
weapon_desc           77
status_desc            6
crm_cd_1             119
crm_cd_2             102
crm_cd_3              27
location           53316
cross_street        7253
lat                 5228
lon                 4891
dtype: int64

Worth noting here that there are no duplicate rows here since the Division of Records Numbers which are the official file numbers 'dr_no' are all unique.

Not many status_desc value types, lets see what they are:

In [250]:
df['status_desc'].value_counts()

Invest Cont     322960
Adult Other      41274
Adult Arrest     34125
Juv Arrest        1192
Juv Other          593
UNK                  2
Name: status_desc, dtype: int64

<h4 id= ""; style="color:#c8d43e; text-align:left; padding: 0px; border-bottom: 1px solid #c8d43e;">LATITUDE AND LONGITUDE VALUES</h4>

Some of the lat and long values are zeros:

In [251]:
# df[df['lat'] ==0][['lat', 'lon']]
df_ll_nulls = df[df['lat'] ==0][['area', 'rpt_dist_no', 'location', 'premis_cd', 'premis_desc', 'lat', 'lon']].copy()
df_ll_complete = df[df['lat'] !=0][['area', 'rpt_dist_no', 'location', 'premis_cd', 'premis_desc', 'lat', 'lon']].copy()

print(f'Sum total of missing latitudes: {df_ll_nulls.shape[0]}\n')

print('df_ll_nulls.nunique()\n-------------------')
display(df_ll_nulls.nunique())

df_ll_nulls.head()

Sum total of missing latitudes: 1222

df_ll_nulls.nunique()
-------------------

area             21
rpt_dist_no     579
location       1036
premis_cd        92
premis_desc      92
lat               1
lon               1
dtype: int64

,area,rpt_dist_no,location,premis_cd,premis_desc,lat,lon
120,6,639,5400 HOLLYWOOD BL,203.0,OTHER BUSINESS,0.0,0.0
297,6,636,SUNSET,101.0,STREET,0.0,0.0
542,6,659,1300 N HARVARD BL,502.0,"MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)",0.0,0.0
805,6,639,HOLLYWOOD,102.0,SIDEWALK,0.0,0.0
892,19,1998,7800 VAN NUYS BL,101.0,STREET,0.0,0.0

In [252]:
df_ll_complete[['area', 'rpt_dist_no', 'lat']].groupby(['area', 'rpt_dist_no']).agg(['min', 'max', 'mean']).head(3)

                      lat
                      min      max       mean
area rpt_dist_no
1    101          34.0646  34.0737  34.067726
     105          34.0668  34.0736  34.070898
     109          34.0717  34.0761  34.074850

Removing the lat values = to 0 for unskewed mean calculations

In [253]:
df_ll_complete[['area', 'rpt_dist_no', 'lat']].groupby(['area', 'rpt_dist_no']).agg(['min', 'max', 'mean']).tail(3)

                      lat
                      min      max       mean
area rpt_dist_no
21   2196         34.1449  34.1587  34.152467
     2197         34.1474  34.1632  34.155694
     2198         34.1438  34.1492  34.146836

by the above head and tail prints, we can see that the `rpt_dist_no` values are unique to each `area` and are identified by the leading numbers.  Using the unique `rpt_dist_no` as a key, I can build a dictionary for the mean values we can impute the missing `lat` and `lon` values with higher accuracy.

Create a dictionary to key rpt_dist_no to mean lat and long:

In [254]:
# Create a dictionary to key rpt_dist_no to mean lat:
lat_impute_dict = df_ll_complete[['rpt_dist_no', 'lat']].groupby(['rpt_dist_no']).agg(['mean']).round(4).to_dict()

#The code above creates a nested dictionary, so to extract sut the dictionary we want:
lat_impute_dict = lat_impute_dict[('lat', 'mean')]
lat_impute_dict

{101: 34.0677,
 105: 34.0709,
 109: 34.0749,
 111: 34.0611,
 112: 34.0563,
 118: 34.0651,
 119: 34.0563,
 121: 34.0604,
 122: 34.057,
 123: 34.0541,
 124: 34.0528,
 127: 34.0521,
 128: 34.0501,
 129: 34.0511,
 131: 34.0569,
 132: 34.0548,
 133: 34.0521,
 134: 34.0508,
 135: 34.0498,
 138: 34.0475,
 139: 34.0461,
 141: 34.0542,
 142: 34.0521,
 143: 34.049,
 144: 34.048,
 145: 34.0474,
 146: 34.0462,
 147: 34.0452,
 148: 34.0443,
 151: 34.0504,
 152: 34.0494,
 153: 34.0469,
 154: 34.0464,
 155: 34.0449,
 156: 34.044,
 157: 34.0426,
 158: 34.0398,
 159: 34.0395,
 161: 34.0483,
 162: 34.0467,
 163: 34.0444,
 164: 34.0452,
 165: 34.0436,
 166: 34.0422,
 171: 34.0456,
 174: 34.0435,
 176: 34.0411,
 181: 34.043,
 182: 34.0423,
 185: 34.0399,
 191: 34.0382,
 192: 34.0373,
 195: 34.0334,
 201: 34.0875,
 202: 34.089,
 203: 34.085,
 204: 34.0853,
 205: 34.0802,
 211: 34.0809,
 212: 34.0788,
 213: 34.0772,
 215: 34.0756,
 216: 34.075,
 217: 34.0732,
 218: 34.0734,
 219: 34.0675,
 221: 34.0774,
 231: 34.0716,
 233: 34.0696,
 234: 34.0648,
 235: 34.0679,
 236: 34.0662,
 237: 34.0617,
 238: 34.064,
 239: 34.0601,
 241: 34.066,
 245: 34.0611,
 246: 34.0597,
 247: 34.0597,
 248: 34.0582,
 249: 34.0538,
 251: 34.0625,
 256: 34.0566,
 257: 34.0553,
 261: 34.0572,
 265: 34.0552,
 266: 34.0535,
 267: 34.0552,
 269: 34.0512,
 271: 34.0532,
 275: 34.0507,
 277: 34.0585,
 279: 34.0483,
 281: 34.0493,
 285: 34.0471,
 289: 34.0454,
 291: 34.0446,
 292: 34.0388,
 295: 34.0429,
 299: 34.0411,
 301: 34.0334,
 303: 34.0331,
 305: 34.0335,
 307: 34.0336,
 308: 34.0346,
 309: 34.0372,
 311: 34.0291,
 312: 34.0289,
 313: 34.0329,
 314: 34.0325,
 315: 34.0334,
 316: 34.0348,
 317: 34.0347,
 318: 34.0348,
 319: 34.0318,
 321: 34.0242,
 325: 34.0311,
 326: 34.0316,
 327: 34.031,
 328: 34.0265,
 329: 34.0251,
 331: 34.028,
 332: 34.0288,
 333: 34.0282,
 334: 34.0279,
 335: 34.0277,
 336: 34.0281,
 337: 34.0275,
 338: 34.027,
 341: 34.0184,
 343: 34.0201,
 351: 34.0226,
 353: 34.0212,
 354: 34.0234,
 355: 34.0223,
 356: 34.0221,
 357: 34.0216,
 358: 34.0215,
 359: 34.0172,
 361: 34.0169,
 362: 34.0168,
 363: 34.0126,
 373: 34.0172,
 374: 34.015,
 375: 34.0146,
 376: 34.0151,
 377: 34.015,
 378: 34.015,
 379: 34.0148,
 391: 34.0059,
 392: 34.0003,
 393: 34.0075,
 394: 34.0078,
 395: 34.0085,
 396: 34.0075,
 397: 34.0078,
 398: 34.0079,
 399: 34.0075,
 401: 34.091,
 402: 34.0911,
 403: 34.0998,
 404: 34.1058,
 405: 34.1115,
 406: 34.0978,
 407: 34.0875,
 408: 34.0877,
 409: 34.0934,
 411: 34.0763,
 412: 34.079,
 413: 34.082,
 414: 34.082,
 415: 34.0754,
 416: 34.0806,
 417: 34.0796,
 418: 34.0937,
 421: 34.0691,
 422: 34.0707,
 423: 34.0649,
 424: 34.07,
 426: 34.0856,
 427: 34.0817,
 428: 34.0806,
 429: 34.0871,
 437: 34.0676,
 438: 34.0756,
 439: 34.0683,
 441: 34.0563,
 442: 34.0577,
 443: 34.0609,
 445: 34.0568,
 448: 34.0588,
 449: 34.0527,
 451: 34.0494,
 452: 34.0502,
 453: 34.0514,
 454: 34.0459,
 455: 34.0505,
 456: 34.0499,
 457: 34.0471,
 459: 34.0449,
 461: 34.0456,
 462: 34.0393,
 463: 34.0462,
 464: 34.0449,
 465: 34.0344,
 466: 34.0438,
 467: 34.04,
 468: 34.038,
 469: 34.0341,
 471: 34.038,
 473: 34.0379,
 477: 34.0331,
 478: 34.0287,
 479: 34.0254,
 483: 34.0314,
 487: 34.0275,
 488: 34.024,
 489: 34.0254,
 491: 34.0242,
 497: 34.0202,
 499: 34.0186,
 501: 33.8653,
 502: 33.8696,
 503: 33.7939,
 504: 33.8491,
 505: 33.8536,
 506: 33.8314,
 507: 33.8204,
 508: 33.8123,
 509: 33.8,
 511: 33.7923,
 512: 33.7816,
 513: 33.7898,
 514: 33.7888,
 515: 33.7942,
 516: 33.7864,
 517: 33.7861,
 518: 33.7978,
 519: 33.7934,
 521: 33.7645,
 522: 33.7793,
 523: 33.7584,
 524: 33.7752,
 525: 33.7741,
 526: 33.7797,
 527: 33.7672,
 528: 33.7869,
 529: 33.7785,
 531: 33.787,
 532: 33.7854,
 541: 33.7539,
 551: 33.7442,
 555: 33.7472,
 557: 33.7409,
 558: 33.7463,
 559: 33.742,
 561: 33.7331,
 562: 33.7336,
 563: 33.7321,
 564: 33.7411,
 565: 33.7365,
 566: 33.7346,
 567: 33.7282,
 569: 33.7275,
 581: 33.7249,
 583: 33.7218,
 584: 33.7155,
 585: 33.7243,
 587: 33.7142,
 589: 33.7145,
 599: 33.7315,
 600: 34.0575,
 615: 34.1257,
 621: 34.1174,
 622: 34.1102,
 625: 34.1099,
 626: 34.1097,
 627: 34.118,
 628: 34.1073,
 629: 34.1147,
 631: 34.097,
 632: 34.1005,
 635: 34.1071,
 636: 34.1027,
 637: 34.1029,
 638: 34.1036,
 639: 34.1034,
 642: 34.0976,
 643: 34.1005,
 644: 34.0961,
 645: 34.1005,
 646: 34.0992,
 647: 34.0999,
 648: 34.1002,
 649: 34.0998,
 656: 34.089,
 657: 34.0891,
 659: 34.0969,
 663: 34.091,
 665: 34.09,
 666: 34.0947,
 667: 34.0939,
 668: 34.0954,
 669: 34.0926,
 676: 34.0849,
 677: 34.0862,
 678: 34.0864,
 679: 34.0883,
 697: 34.0835,
 700: 34.0543,
 701: 34.0844,
 702: 34.0838,
 704: 34.0848,
 705: 34.0844,
 706: 34.0837,
 711: 34.0774,
 713: 34.0776,
 714: 34.0777,
 715: 34.078,
 716: 34.0689,
 717: 34.0774,
 719: 34.0795,
 721: 34.0744,
 722: 34.0734,
 723: 34.0731,
 724: 34.0741,
 725: 34.0733,
 726: 34.0728,
 727: 34.0723,
 728: 34.0838,
 729: 34.073,
 732: 34.0661,
 733: 34.064,
 734: 34.0687,
 735: 34.0636,
 736: 34.067,
 737: 34.0638,
 738: 34.0641,
 739: 34.0659,
 742: 34.0617,
 743: 34.0598,
 745: 34.0582,
 747: 34.057,
 749: 34.0591,
 752: 34.056,
 753: 34.0548,
 755: 34.0506,
 758: 34.0518,
 759: 34.0499,
 762: 34.0499,
 763: 34.048,
 764: 34.0468,
 765: 34.0493,
 766: 34.0472,
 767: 34.0467,
 768: 34.0441,
 769: 34.0459,
 772: 34.0353,
 773: 34.0423,
 774: 34.0433,
 775: 34.0429,
 776: 34.0439,
 777: 34.043,
 778: 34.0422,
 779: 34.0419,
 782: 34.0384,
 783: 34.0372,
 784: 34.0381,
 785: 34.0377,
 787: 34.038,
 788: 34.0385,
 789: 34.0383,
 801: 34.0763,
 802: 34.0555,
 803: 34.074,
 804: 34.1081,
 805: 34.0921,
 806: 34.0925,
 807: 34.1118,
 808: 34.1114,
 809: 34.1092,
 811: 34.048,
 812: 34.0661,
 813: 34.0717,
 814: 34.0671,
 815: 34.0706,
 816: 34.0673,
 817: 34.0621,
 818: 34.0705,
 819: 34.073,
 821: 34.0382,
 822: 34.0434,
 823: 34.0414,
 824: 34.0376,
 825: 34.0538,
 826: 34.0557,
 827: 34.0582,
 828: 34.0647,
 829: 34.0618,
 831: 34.0479,
 832: 34.0513,
 833: 34.0566,
 834: 34.0583,
 835: 34.047,
 836: 34.0532,
 837: 34.0678,
 838: 34.0643,
 839: 34.0605,
 841: 34.0427,
 842: 34.0473,
 843: 34.1264,
 847: 34.0481,
 848: 34.0542,
 849: 34.0587,
 851: 34.0384,
 852: 34.0421,
 853: 34.0452,
 854: 34.0471,
 855: 34.0511,
 857: 34.0546,
 858: 34.0529,
 859: 34.0514,
 861: 34.0394,
 871: 34.0333,
 872: 34.0266,
 881: 34.0342,
 882: 34.0388,
 883: 34.0398,
 884: 34.0392,
 885: 34.0402,
 886: 34.0504,
 887: 34.0433,
 889: 34.0422,
 891: 34.0296,
 892: 34.033,
 893: 34.0343,
 895: 34.0326,
 896: 34.0311,
 897: 34.0319,
 898: 34.0364,
 899: 34.0333,
 900: 34.1837,
 901: 34.2066,
 904: 34.2085,
 905: 34.2047,
 906: 34.2043,
 909: 34.2038,
 911: 34.1955,
 914: 34.1978,
 915: 34.198,
 916: 34.1976,
 917: 34.1962,
 919: 34.1956,
 921: 34.1739,
 922: 34.1907,
 923: 34.1905,
 926: 34.1903,
 929: 34.1882,
 931: 34.1839,
 932: 34.1837,
 933: 34.1834,
 935: 34.1839,
 937: 34.1838,
 938: 34.1828,
 939: 34.1808,
 941: 34.1756,
 942: 34.1802,
 943: 34.1745,
 946: 34.1754,
 948: 34.1728,
 952: 34.1687,
 955: 34.1665,
 957: 34.1671,
 958: 34.1684,
 961: 34.1602,
 963: 34.1622,
 964: 34.1591,
 966: 34.1607,
 969: 34.1606,
 971: 34.1555,
 974: 34.1543,
 976: 34.1526,
 979: 34.1529,
 981: 34.1516,
 983: 34.1867,
 984: 34.15,
 985: 34.1504,
 989: 34.1491,
 991: 34.1408,
 994: 34.1392,
 998: 34.1427,
 1001: 34.2145,
 1003: 34.2149,
 1004: 34.2147,
 1005: 34.2148,
 1006: 34.2155,
 1007: 34.2149,
 1008: 34.207,
 1009: 34.2208,
 1011: 34.2037,
 1012: 34.2037,
 1015: 34.2039,
 1016: 34.1905,
 1017: 34.2052,
 1018: 34.2072,
 1019: 34.2055,
 1021: 34.1957,
 1023: 34.194,
 1024: 34.1959,
 1025: 34.1983,
 1027: 34.1972,
 1028: 34.1937,
 1029: 34.198,
 1031: 34.1866,
 1033: 34.185,
 1034: 34.1829,
 1035: 34.1908,
 1037: 34.1903,
 1039: 34.1904,
 1041: 34.1773,
 1042: 34.1722,
 1043: 34.1768,
 1044: 34.1767,
 1045: 34.1754,
 1046: 34.1775,
 1047: 34.1747,
 1048: 34.1779,
 1049: 34.1791,
 1061: 34.1712,
 1063: 34.1697,
 1065: 34.1674,
 1067: 34.1663,
 1068: 34.1674,
 1075: 34.1632,
 1077: 34.1604,
 1078: 34.1614,
 1079: 34.1591,
 1083: 34.154,
 1087: 34.165,
 1088: 34.1558,
 1089: 34.154,
 1091: 34.1507,
 1094: 34.1501,
 1097: 34.1432,
 1098: 34.1334,
 1099: 34.142,
 1101: 34.1331,
 1102: 34.1345,
 1105: 34.1422,
 1107: 34.1281,
 1109: 34.1408,
 1112: 34.1273,
 1113: 34.1395,
 1115: 34.1373,
 1116: 34.1148,
 1117: 34.1298,
 1118: 34.1134,
 1119: 34.135,
 1122: 34.1172,
 1123: 34.121,
 1124: 34.1178,
 1125: 34.1221,
 1126: 34.1219,
 1127: 34.1196,
 1128: 34.1191,
 1129: 34.1169,
 1132: 34.1132,
 1133: 34.1129,
 1134: 34.1085,
 1135: 34.1144,
 1136: 34.1197,
 1137: 34.1103,
 1138: 34.1153,
 1139: 34.1092,
 1141: 34.106,
 1142: 34.1073,
 1143: 34.1055,
 1144: 34.1017,
 1145: 34.1028,
 1146: 34.1014,
 1147: 34.1002,
 1148: 34.1029,
 1149: 34.1072,
 1151: 34.0985,
 1152: 34.0992,
 1153: 34.1086,
 1157: 34.0967,
 1158: 34.0935,
 1159: 34.099,
 1161: 34.0924,
 1162: 34.0954,
 1163: 34.0931,
 1169: 34.1042,
 1171: 34.0913,
 1172: 34.0878,
 1173: 34.0913,
 1174: 34.091,
 1175: 34.0865,
 1176: 34.09,
 1177: 34.0881,
 1178: 34.0926,
 1179: 34.0917,
 1181: 34.0804,
 1183: 34.0825,
 1184: 34.0798,
 1185: 34.0774,
 1186: 34.0814,
 1189: 34.086,
 1195: 34.0724,
 1199: 34.0766,
 1203: 34.0001,
 1204: 34.0019,
 1205: 33.9976,
 1207: 34.0001,
 1208: 34.0001,
 1209: 33.9998,
 1211: 33.9923,
 1213: 33.9921,
 1215: 33.992,
 1218: 33.9922,
 1219: 33.9929,
 1231: 33.986,
 1232: 33.988,
 1233: 33.9876,
 1235: 33.9866,
 1239: 33.9866,
 1241: 33.982,
 1242: 33.9821,
 1243: 33.9792,
 1245: 33.9792,
 1248: 33.9794,
 1249: 33.9791,
 1251: 33.9745,
 1252: 33.975,
 1253: 33.9717,
 1255: 33.9719,
 1256: 33.9731,
 1257: 33.9695,
 1258: 33.9715,
 1259: 33.9717,
 1263: 33.9635,
 1265: 33.9631,
 1266: 33.9662,
 1267: 33.9624,
 1268: 33.9641,
 1269: 33.9642,
 1273: 33.9572,
 1283: 33.9485,
 1293: 33.9419,
 1300: 34.0087,
 1303: 34.0347,
 1307: 34.0369,
 1309: 34.027,
 1311: 34.0335,
 1313: 34.0287,
 1317: 34.0244,
 1321: 34.0292,
 1322: 34.0245,
 1323: 34.0219,
 1324: 34.0211,
 1325: 34.0171,
 1326: 34.0157,
 1327: 34.0174,
 1331: 34.0232,
 1333: 34.0175,
 1341: 34.0154,
 1342: 34.0147,
 1343: 34.0116,
 1344: 34.008,
 1345: 34.011,
 1346: 34.0063,
 1347: 34.0092,
 1351: 34.0076,
 1352: 34.0039,
 1353: 34.004,
 1354: 34.0086,
 1361: 34.0,
 1362: 33.998,
 1363: 33.9984,
 1364: 33.9993,
 1365: 33.9994,
 1367: 33.9997,
 1371: 33.9925,
 1372: 33.9926,
 1373: 33.9929,
 1375: 33.9924,
 1377: 33.9927,
 1381: 33.9861,
 1383: 33.9856,
 1385: 33.9856,
 1391: 33.979,
 1393: 33.9784,
 1394: 33.9786,
 1395: 33.9784,
 1400: 33.9753,
 1401: 34.0253,
 1402: 34.028,
 1403: 34.0298,
 1405: 34.0305,
 1406: 34.024,
 1407: 34.0253,
 1408: 34.029,
 1409: 34.0276,
 1411: 33.9922,
 1412: 33.9935,
 1413: 33.9958,
 1414: 33.9979,
 1415: 34.0013,
 1416: 34.0094,
 1424: 34.0174,
 1425: 34.0213,
 1426: 34.0225,
 1427: 34.0245,
 1428: 34.0264,
 1431: 33.9877,
 1432: 33.9932,
 1433: 33.9972,
 1434: 34.0026,
 1435: 34.0101,
 1436: 34.0144,
 1437: 34.0163,
 1438: 34.0198,
 1441: 33.9837,
 1443: 33.9925,
 1444: 33.9878,
 1445: 33.9995,
 1446: 34.0028,
 1449: 34.0056,
 1451: 33.9724,
 1452: 33.9749,
 1453: 33.9908,
 1454: 33.9845,
 1455: 33.9896,
 1456: 33.9956,
 1457: 33.9917,
 1458: 33.998,
 1459: 33.9999,
 1462: 33.9715,
 1463: 33.9773,
 1464: 33.9758,
 1465: 33.9861,
 1466: 33.9748,
 1467: 33.9739,
 1468: 33.9934,
 1469: 33.9759,
 1471: 33.9571,
 1472: 33.9587,
 1473: 33.961,
 1474: 33.9634,
 1475: 33.9666,
 1476: 33.9639,
 1477: 33.9646,
 1479: 33.9657,
 1483: 33.957,
 1484: 33.959,
 1485: 33.9579,
 1486: 33.9569,
 1487: 33.9571,
 1488: 33.9529,
 1489: 33.9484,
 1491: 33.9331,
 1492: 33.9414,
 1493: 33.9294,
 1494: 33.9439,
 1495: 33.9523,
 1496: 33.9465,
 1497: 33.9448,
 1498: 33.9374,
 1499: 33.9311,
 1501: 34.2117,
 1502: 34.2103,
 1503: 34.1996,
 1504: 34.205,
 1505: 34.2029,
 1506: 34.2032,
 1508: 34.2061,
 1509: 34.2026,
 1511: 34.2035,
 1512: 34.1975,
 1513: 34.196,
 1514: 34.1941,
 1515: 34.1956,
 1516: 34.193,
 1517: 34.1928,
 1519: 34.1911,
 1521: 34.1983,
 1522: 34.1949,
 1523: 34.1853,
 1524: 34.1867,
 1525: 34.1846,
 1526: 34.1842,
 1527: 34.1852,
 1529: 34.1826,
 1531: 34.1741,
 1532: 34.1794,
 1533: 34.1754,
 1535: 34.1757,
 1537: 34.1761,
 1538: 34.175,
 1539: 34.1746,
 1541: 34.1636,
 1542: 34.1711,
 1543: 34.168,
 1544: 34.1617,
 1545: 34.1648,
 1546: 34.1639,
 1547: 34.1692,
 1548: 34.1664,
 1549: 34.17,
 1551: 34.157,
 1553: 34.1563,
 1555: 34.1608,
 1557: 34.16,
 1559: 34.1577,
 1562: 34.1531,
 1563: 34.1508,
 1565: 34.1495,
 1566: 34.1498,
 1567: 34.1502,
 1569: 34.1504,
 1581: 34.148,
 1583: 34.1459,
 1585: 34.1425,
 1586: 34.141,
 1587: 34.1381,
 1588: 34.1338,
 1589: 34.1385,
 1591: 34.1403,
 1595: 34.1404,
 1596: 34.1376,
 1599: 34.1301,
 1601: 34.2859,
 1602: 34.2812,
 1603: 34.2902,
 1605: 34.2825,
 1606: 34.2784,
 1608: 34.2767,
 1611: 34.2802,
 1612: 34.2733,
 1613: 34.2759,
 1614: 34.2804,
 1615: 34.2754,
 1617: 34.265,
 1618: 34.2709,
 1619: 34.2693,
 1621: 34.2625,
 1622: 34.269,
 1623: 34.268,
 1633: 34.2723,
 1634: 34.2725,
 1635: 34.2724,
 1636: 34.263,
 1637: 34.2632,
 1638: 34.2587,
 1639: 34.2577,
 1641: 34.2551,
 1642: 34.258,
 1643: 34.2609,
 1645: 34.2636,
 1651: 34.2457,
 1653: 34.2516,
 1654: 34.2578,
 1655: 34.2554,
 1656: 34.2572,
 1657: 34.2524,
 1658: 34.2511,
 1659: 34.2491,
 1661: 34.2379,
 1663: 34.2369,
 1664: 34.2429,
 1665: 34.2477,
 1666: 34.2674,
 1667: 34.2407,
 1668: 34.2476,
 1669: 34.2406,
 1671: 34.2284,
 1672: 34.2316,
 1673: 34.228,
 1675: 34.2305,
 1676: 34.2265,
 1677: 34.2183,
 1678: 34.2324,
 1679: 34.2336,
 1681: 34.2237,
 1682: 34.2276,
 1683: 34.2368,
 1684: 34.2152,
 1685: 34.2157,
 1687: 34.2177,
 1689: 34.2207,
 1691: 34.2171,
 1693: 34.2116,
 1695: 34.2108,
 1698: 34.2144,
 1699: 34.2098,
 1701: 34.281,
 1703: 34.2939,
 1705: 34.3077,
 1707: 34.2975,
 1708: 34.2879,
 1709: 34.2812,
 1712: 34.2797,
 1713: 34.2789,
 1714: 34.2856,
 1715: 34.2893,
 1716: 34.2864,
 1717: 34.2758,
 1718: 34.2756,
 1719: 34.2784,
 1721: 34.2657,
 1722: 34.2602,
 1723: 34.2628,
 1725: 34.2632,
 1727: 34.2652,
 1728: 34.2703,
 1729: 34.2756,
 1732: 34.25,
 1735: 34.2681,
 1737: 34.2699,
 1738: 34.269,
 1739: 34.2657,
 1743: 34.2601,
 1745: 34.2618,
 1747: 34.2622,
 1749: 34.2608,
 1751: 34.2531,
 1752: 34.2539,
 1753: 34.2535,
 1754: 34.2544,
 1755: 34.2543,
 1756: 34.254,
 1757: 34.2553,
 1758: 34.254,
 1759: 34.254,
 1761: 34.2432,
 1762: 34.2471,
 1763: 34.254,
 1764: 34.2415,
 1765: 34.2533,
 1766: 34.2458,
 1767: 34.2435,
 1768: 34.2471,
 1771: 34.2408,
 1772: 34.241,
 1773: 34.2384,
 1774: 34.2466,
 1775: 34.2388,
 1776: 34.2437,
 1777: 34.2414,
 1778: 34.2483,
 1779: 34.2404,
 1781: 34.2319,
 1782: 34.2305,
 1783: 34.236,
 1784: 34.2282,
 1785: 34.234,
 1787: 34.2439,
 1788: 34.232,
 1791: 34.2248,
 1792: 34.2243,
 1793: 34.2274,
 1794: 34.2251,
 1795: 34.224,
 1796: 34.2287,
 1797: 34.2289,
 1798: 34.2324,
 1799: 34.2245,
 1801: 33.9561,
 1802: 33.9562,
 1803: 33.9588,
 1804: 33.9588,
 1805: 33.9542,
 1806: 33.9545,
 1821: 33.9469,
 1822: 33.9469,
 1823: 33.9465,
 1824: 33.9474,
 1826: 33.9492,
 1827: 33.9485,
 1829: 33.9463,
 1831: 33.9198,
 1832: 33.9404,
 1834: 33.9397,
 1835: 33.9414,
 1836: 33.9388,
 1837: 33.9364,
 1838: 33.9405,
 1839: 33.9389,
 1841: 33.937,
 1842: 33.9352,
 1844: 33.9346,
 1846: 33.9319,
 1849: 33.9321,
 1851: 33.9131,
 1861: 33.9282,
 1862: 33.9269,
 1863: 33.9275,
 1864: 33.9265,
 1871: 33.9026,
 1881: 33.8881,
 ...}

In [255]:
# Create a dictionary to key rpt_dist_no to mean long:
lon_impute_dict = df_ll_complete[['rpt_dist_no', 'lon']].groupby(['rpt_dist_no']).agg(['mean']).round(4).to_dict()

#The code above creates a nested dictionary, so to extract sut the dictionary we want:
lon_impute_dict = lon_impute_dict[('lon', 'mean')]
lon_impute_dict

{101: -118.2464,
 105: -118.2323,
 109: -118.228,
 111: -118.2417,
 112: -118.2434,
 118: -118.2314,
 119: -118.2359,
 121: -118.2498,
 122: -118.2481,
 123: -118.245,
 124: -118.2433,
 127: -118.2414,
 128: -118.2406,
 129: -118.2334,
 131: -118.2539,
 132: -118.2503,
 133: -118.2472,
 134: -118.2486,
 135: -118.2458,
 138: -118.2418,
 139: -118.2351,
 141: -118.2565,
 142: -118.2532,
 143: -118.25,
 144: -118.2484,
 145: -118.2474,
 146: -118.2464,
 147: -118.2443,
 148: -118.242,
 151: -118.2596,
 152: -118.2562,
 153: -118.2518,
 154: -118.2491,
 155: -118.2471,
 156: -118.2455,
 157: -118.2438,
 158: -118.2411,
 159: -118.2344,
 161: -118.2628,
 162: -118.2581,
 163: -118.254,
 164: -118.2508,
 165: -118.2487,
 166: -118.2468,
 171: -118.2656,
 174: -118.2523,
 176: -118.2506,
 181: -118.2691,
 182: -118.2627,
 185: -118.2573,
 191: -118.2717,
 192: -118.2668,
 195: -118.2622,
 201: -118.2965,
 202: -118.2886,
 203: -118.2886,
 204: -118.2812,
 205: -118.2758,
 211: -118.2962,
 212: -118.2886,
 213: -118.2844,
 215: -118.2777,
 216: -118.2683,
 217: -118.2636,
 218: -118.2578,
 219: -118.2512,
 221: -118.2957,
 231: -118.2821,
 233: -118.2781,
 234: -118.2583,
 235: -118.2727,
 236: -118.2682,
 237: -118.2615,
 238: -118.2568,
 239: -118.2536,
 241: -118.2826,
 245: -118.2774,
 246: -118.2741,
 247: -118.2703,
 248: -118.2645,
 249: -118.2618,
 251: -118.2811,
 256: -118.2715,
 257: -118.2671,
 261: -118.2816,
 265: -118.277,
 266: -118.2732,
 267: -118.2649,
 269: -118.2675,
 271: -118.2819,
 275: -118.2767,
 277: -118.2725,
 279: -118.2713,
 281: -118.2823,
 285: -118.2775,
 289: -118.2736,
 291: -118.2827,
 292: -118.2827,
 295: -118.28,
 299: -118.2766,
 301: -118.3647,
 303: -118.3523,
 305: -118.3439,
 307: -118.3369,
 308: -118.281,
 309: -118.277,
 311: -118.3661,
 312: -118.3561,
 313: -118.3312,
 314: -118.3231,
 315: -118.3124,
 316: -118.305,
 317: -118.2955,
 318: -118.288,
 319: -118.2763,
 321: -118.368,
 325: -118.292,
 326: -118.3027,
 327: -118.2864,
 328: -118.2808,
 329: -118.2771,
 331: -118.35,
 332: -118.3428,
 333: -118.3377,
 334: -118.3324,
 335: -118.3229,
 336: -118.3129,
 337: -118.3016,
 338: -118.2891,
 341: -118.3679,
 343: -118.3602,
 351: -118.3522,
 353: -118.3406,
 354: -118.3227,
 355: -118.3127,
 356: -118.3041,
 357: -118.2949,
 358: -118.2865,
 359: -118.2814,
 361: -118.3532,
 362: -118.3479,
 363: -118.3407,
 373: -118.3327,
 374: -118.3214,
 375: -118.3121,
 376: -118.3047,
 377: -118.2982,
 378: -118.2871,
 379: -118.2933,
 391: -118.3508,
 392: -118.325,
 393: -118.3297,
 394: -118.3201,
 395: -118.3099,
 396: -118.2894,
 397: -118.2974,
 398: -118.2849,
 399: -118.2824,
 401: -118.2068,
 402: -118.2019,
 403: -118.1981,
 404: -118.1835,
 405: -118.1782,
 406: -118.1842,
 407: -118.1883,
 408: -118.1786,
 409: -118.1647,
 411: -118.2226,
 412: -118.2178,
 413: -118.2134,
 414: -118.2101,
 415: -118.2125,
 416: -118.2044,
 417: -118.1967,
 418: -118.1745,
 421: -118.2195,
 422: -118.2117,
 423: -118.2122,
 424: -118.2014,
 426: -118.1751,
 427: -118.1856,
 428: -118.1754,
 429: -118.1656,
 437: -118.1878,
 438: -118.1717,
 439: -118.1727,
 441: -118.2232,
 442: -118.2142,
 443: -118.2052,
 445: -118.2091,
 448: -118.1965,
 449: -118.1974,
 451: -118.2264,
 452: -118.2218,
 453: -118.2184,
 454: -118.2197,
 455: -118.2095,
 456: -118.2013,
 457: -118.2039,
 459: -118.1961,
 461: -118.2246,
 462: -118.2198,
 463: -118.2153,
 464: -118.2114,
 465: -118.2009,
 466: -118.206,
 467: -118.2079,
 468: -118.1994,
 469: -118.1952,
 471: -118.2241,
 473: -118.2164,
 477: -118.2121,
 478: -118.2023,
 479: -118.1961,
 483: -118.2201,
 487: -118.2148,
 488: -118.2058,
 489: -118.2154,
 491: -118.2217,
 497: -118.2121,
 499: -118.1989,
 501: -118.2917,
 502: -118.2968,
 503: -118.291,
 504: -118.3035,
 505: -118.293,
 506: -118.3049,
 507: -118.3041,
 508: -118.3056,
 509: -118.3042,
 511: -118.3042,
 512: -118.3044,
 513: -118.2926,
 514: -118.2779,
 515: -118.2696,
 516: -118.2658,
 517: -118.2596,
 518: -118.2612,
 519: -118.2434,
 521: -118.2963,
 522: -118.2718,
 523: -118.2876,
 524: -118.2762,
 525: -118.2674,
 526: -118.2651,
 527: -118.2664,
 528: -118.2481,
 529: -118.2513,
 531: -118.3038,
 532: -118.2723,
 541: -118.3031,
 551: -118.309,
 555: -118.2928,
 557: -118.2916,
 558: -118.2827,
 559: -118.2623,
 561: -118.3124,
 562: -118.3046,
 563: -118.2933,
 564: -118.2833,
 565: -118.2911,
 566: -118.2836,
 567: -118.2848,
 569: -118.278,
 581: -118.3189,
 583: -118.3094,
 584: -118.2983,
 585: -118.2949,
 587: -118.2904,
 589: -118.2848,
 599: -118.2399,
 600: -118.3599,
 615: -118.3358,
 621: -118.3842,
 622: -118.3578,
 625: -118.339,
 626: -118.3287,
 627: -118.3206,
 628: -118.3218,
 629: -118.3147,
 631: -118.3883,
 632: -118.37,
 635: -118.3338,
 636: -118.3331,
 637: -118.323,
 638: -118.3151,
 639: -118.3051,
 642: -118.3574,
 643: -118.3486,
 644: -118.3487,
 645: -118.3411,
 646: -118.3328,
 647: -118.3225,
 648: -118.3105,
 649: -118.3041,
 656: -118.3271,
 657: -118.3118,
 659: -118.3044,
 663: -118.3379,
 665: -118.3367,
 666: -118.3271,
 667: -118.319,
 668: -118.3115,
 669: -118.3047,
 676: -118.327,
 677: -118.3145,
 678: -118.3066,
 679: -118.3025,
 697: -118.3146,
 700: -118.3402,
 701: -118.3692,
 702: -118.3544,
 704: -118.3765,
 705: -118.3461,
 706: -118.34,
 711: -118.3703,
 713: -118.3581,
 714: -118.3511,
 715: -118.3461,
 716: -118.344,
 717: -118.3411,
 719: -118.3265,
 721: -118.3806,
 722: -118.3736,
 723: -118.3647,
 724: -118.3565,
 725: -118.3511,
 726: -118.346,
 727: -118.3416,
 728: -118.3584,
 729: -118.3249,
 732: -118.3653,
 733: -118.3551,
 734: -118.3547,
 735: -118.3472,
 736: -118.3456,
 737: -118.3428,
 738: -118.3374,
 739: -118.327,
 742: -118.3659,
 743: -118.358,
 745: -118.3482,
 747: -118.3388,
 749: -118.3249,
 752: -118.3712,
 753: -118.3622,
 755: -118.3534,
 758: -118.3309,
 759: -118.3217,
 762: -118.372,
 763: -118.3644,
 764: -118.3543,
 765: -118.3417,
 766: -118.3298,
 767: -118.3253,
 768: -118.3746,
 769: -118.3206,
 772: -118.3779,
 773: -118.3579,
 774: -118.3478,
 775: -118.3423,
 776: -118.3371,
 777: -118.3333,
 778: -118.3273,
 779: -118.3208,
 782: -118.3725,
 783: -118.3594,
 784: -118.3503,
 785: -118.3425,
 787: -118.3349,
 788: -118.3294,
 789: -118.3232,
 801: -118.5611,
 802: -118.5229,
 803: -118.5045,
 804: -118.4915,
 805: -118.4686,
 806: -118.4507,
 807: -118.4433,
 808: -118.4258,
 809: -118.403,
 811: -118.5531,
 812: -118.4856,
 813: -118.4758,
 814: -118.4649,
 815: -118.4597,
 816: -118.4536,
 817: -118.4447,
 818: -118.4473,
 819: -118.4316,
 821: -118.5444,
 822: -118.5417,
 823: -118.526,
 824: -118.5111,
 825: -118.4839,
 826: -118.4743,
 827: -118.4671,
 828: -118.4382,
 829: -118.4259,
 831: -118.4729,
 832: -118.4642,
 833: -118.4428,
 834: -118.4331,
 835: -118.4372,
 836: -118.4258,
 837: -118.4516,
 838: -118.4494,
 839: -118.4185,
 841: -118.466,
 842: -118.4593,
 843: -118.4789,
 847: -118.4202,
 848: -118.4118,
 849: -118.38,
 851: -118.4626,
 852: -118.4572,
 853: -118.4494,
 854: -118.4451,
 855: -118.4413,
 857: -118.3938,
 858: -118.3858,
 859: -118.3804,
 861: -118.5587,
 871: -118.5306,
 872: -118.5184,
 881: -118.452,
 882: -118.4429,
 883: -118.439,
 884: -118.4318,
 885: -118.416,
 886: -118.4031,
 887: -118.3936,
 889: -118.3818,
 891: -118.4486,
 892: -118.4405,
 893: -118.4287,
 895: -118.4064,
 896: -118.4006,
 897: -118.396,
 898: -118.3872,
 899: -118.3821,
 900: -118.4465,
 901: -118.4693,
 904: -118.4605,
 905: -118.4523,
 906: -118.4454,
 909: -118.4325,
 911: -118.4692,
 914: -118.4569,
 915: -118.4449,
 916: -118.4358,
 917: -118.4575,
 919: -118.428,
 921: -118.4553,
 922: -118.4531,
 923: -118.4558,
 926: -118.4419,
 929: -118.4247,
 931: -118.4693,
 932: -118.4608,
 933: -118.4518,
 935: -118.4443,
 937: -118.4353,
 938: -118.4263,
 939: -118.4181,
 941: -118.461,
 942: -118.4443,
 943: -118.4451,
 946: -118.4358,
 948: -118.4277,
 952: -118.4601,
 955: -118.4457,
 957: -118.4362,
 958: -118.4356,
 961: -118.464,
 963: -118.4568,
 964: -118.4402,
 966: -118.4263,
 969: -118.4143,
 971: -118.463,
 974: -118.453,
 976: -118.4254,
 979: -118.4184,
 981: -118.4632,
 983: -118.4487,
 984: -118.4514,
 985: -118.4424,
 989: -118.4307,
 991: -118.4621,
 994: -118.436,
 998: -118.4182,
 1001: -118.5535,
 1003: -118.5398,
 1004: -118.5326,
 1005: -118.5229,
 1006: -118.5143,
 1007: -118.5057,
 1008: -118.4929,
 1009: -118.4777,
 1011: -118.5522,
 1012: -118.5392,
 1015: -118.5286,
 1016: -118.536,
 1017: -118.5096,
 1018: -118.4795,
 1019: -118.4746,
 1021: -118.5575,
 1023: -118.5479,
 1024: -118.5395,
 1025: -118.5286,
 1027: -118.5101,
 1028: -118.497,
 1029: -118.4805,
 1031: -118.5563,
 1033: -118.5441,
 1034: -118.53,
 1035: -118.529,
 1037: -118.511,
 1039: -118.4807,
 1041: -118.5498,
 1042: -118.5098,
 1043: -118.5382,
 1044: -118.5335,
 1045: -118.5249,
 1046: -118.536,
 1047: -118.5101,
 1048: -118.5273,
 1049: -118.4905,
 1061: -118.5564,
 1063: -118.5387,
 1065: -118.5229,
 1067: -118.5109,
 1068: -118.499,
 1075: -118.526,
 1077: -118.5098,
 1078: -118.4928,
 1079: -118.4756,
 1083: -118.5445,
 1087: -118.5011,
 1088: -118.4936,
 1089: -118.4751,
 1091: -118.559,
 1094: -118.5274,
 1097: -118.5006,
 1098: -118.4866,
 1099: -118.4782,
 1101: -118.2933,
 1102: -118.2699,
 1105: -118.2169,
 1107: -118.1932,
 1109: -118.1932,
 1112: -118.23,
 1113: -118.2232,
 1115: -118.2112,
 1116: -118.2036,
 1117: -118.2127,
 1118: -118.195,
 1119: -118.1925,
 1122: -118.2715,
 1123: -118.2638,
 1124: -118.2438,
 1125: -118.2116,
 1126: -118.201,
 1127: -118.189,
 1128: -118.1829,
 1129: -118.1762,
 1132: -118.2737,
 1133: -118.2541,
 1134: -118.2382,
 1135: -118.2319,
 1136: -118.221,
 1137: -118.2019,
 1138: -118.1903,
 1139: -118.1889,
 1141: -118.2961,
 1142: -118.2887,
 1143: -118.2781,
 1144: -118.2682,
 1145: -118.2562,
 1146: -118.2459,
 1147: -118.2312,
 1148: -118.2082,
 1149: -118.1982,
 1151: -118.2962,
 1152: -118.2843,
 1153: -118.3052,
 1157: -118.235,
 1158: -118.2153,
 1159: -118.2048,
 1161: -118.2983,
 1162: -118.2881,
 1163: -118.294,
 1169: -118.1977,
 1171: -118.2753,
 1172: -118.2649,
 1173: -118.2544,
 1174: -118.2474,
 1175: -118.2452,
 1176: -118.2351,
 1177: -118.2252,
 1178: -118.2234,
 1179: -118.2096,
 1181: -118.2652,
 1183: -118.2579,
 1184: -118.2528,
 1185: -118.2484,
 1186: -118.2378,
 1189: -118.218,
 1195: -118.2459,
 1199: -118.2336,
 1203: -118.3103,
 1204: -118.2974,
 1205: -118.2982,
 1207: -118.2893,
 1208: -118.2846,
 1209: -118.2821,
 1211: -118.3259,
 1213: -118.3102,
 1215: -118.2971,
 1218: -118.2873,
 1219: -118.2821,
 1231: -118.347,
 1232: -118.3281,
 1233: -118.3092,
 1235: -118.2999,
 1239: -118.2884,
 1241: -118.3319,
 1242: -118.3225,
 1243: -118.3105,
 1245: -118.2966,
 1248: -118.289,
 1249: -118.2838,
 1251: -118.3305,
 1252: -118.3221,
 1253: -118.3102,
 1255: -118.2979,
 1256: -118.2848,
 1257: -118.2846,
 1258: -118.2747,
 1259: -118.2637,
 1263: -118.3097,
 1265: -118.2972,
 1266: -118.2853,
 1267: -118.2847,
 1268: -118.2742,
 1269: -118.2637,
 1273: -118.3084,
 1283: -118.3088,
 1293: -118.3113,
 1300: -118.2694,
 1303: -118.2515,
 1307: -118.2445,
 1309: -118.2334,
 1311: -118.2737,
 1313: -118.2554,
 1317: -118.2442,
 1321: -118.2688,
 1322: -118.2628,
 1323: -118.2573,
 1324: -118.2512,
 1325: -118.2543,
 1326: -118.2495,
 1327: -118.2449,
 1331: -118.2717,
 1333: -118.2621,
 1341: -118.277,
 1342: -118.2709,
 1343: -118.2625,
 1344: -118.2644,
 1345: -118.2549,
 1346: -118.2523,
 1347: -118.2448,
 1351: -118.2774,
 1352: -118.2699,
 1353: -118.2616,
 1354: -118.2722,
 1361: -118.2774,
 1362: -118.2702,
 1363: -118.2616,
 1364: -118.2554,
 1365: -118.2505,
 1367: -118.2439,
 1371: -118.277,
 1372: -118.2713,
 1373: -118.2613,
 1375: -118.2524,
 1377: -118.2438,
 1381: -118.2789,
 1383: -118.2746,
 1385: -118.264,
 1391: -118.279,
 1393: -118.2761,
 1394: -118.2726,
 1395: -118.2658,
 1400: -118.4518,
 1401: -118.4458,
 1402: -118.4376,
 1403: -118.4278,
 1405: -118.4131,
 1406: -118.409,
 1407: -118.4042,
 1408: -118.3938,
 1409: -118.395,
 1411: -118.4789,
 1412: -118.4774,
 1413: -118.4734,
 1414: -118.468,
 1415: -118.4616,
 1416: -118.4483,
 1424: -118.4388,
 1425: -118.4325,
 1426: -118.4284,
 1427: -118.4255,
 1428: -118.418,
 1431: -118.4714,
 1432: -118.4598,
 1433: -118.4534,
 1434: -118.4435,
 1435: -118.4294,
 1436: -118.4215,
 1437: -118.4186,
 1438: -118.4124,
 1441: -118.4655,
 1443: -118.4528,
 1444: -118.4476,
 1445: -118.4372,
 1446: -118.4283,
 1449: -118.4224,
 1451: -118.4621,
 1452: -118.4618,
 1453: -118.4408,
 1454: -118.4368,
 1455: -118.4242,
 1456: -118.4208,
 1457: -118.4165,
 1458: -118.4117,
 1459: -118.4043,
 1462: -118.4313,
 1463: -118.4221,
 1464: -118.4173,
 1465: -118.407,
 1466: -118.3995,
 1467: -118.388,
 1468: -118.4117,
 1469: -118.3735,
 1471: -118.4506,
 1472: -118.4474,
 1473: -118.431,
 1474: -118.4196,
 1475: -118.4097,
 1476: -118.3996,
 1477: -118.3895,
 1479: -118.3784,
 1483: -118.4313,
 1484: -118.4165,
 1485: -118.4017,
 1486: -118.4075,
 1487: -118.3946,
 1488: -118.3825,
 1489: -118.3748,
 1491: -118.4368,
 1492: -118.4393,
 1493: -118.4338,
 1494: -118.4025,
 1495: -118.3906,
 1496: -118.3918,
 1497: -118.3741,
 1498: -118.3743,
 1499: -118.376,
 1501: -118.4196,
 1502: -118.4106,
 1503: -118.3999,
 1504: -118.3921,
 1505: -118.3841,
 1506: -118.3747,
 1508: -118.3675,
 1509: -118.367,
 1511: -118.4211,
 1512: -118.4115,
 1513: -118.4058,
 1514: -118.3946,
 1515: -118.3909,
 1516: -118.3838,
 1517: -118.3752,
 1519: -118.3668,
 1521: -118.4217,
 1522: -118.4167,
 1523: -118.4097,
 1524: -118.3977,
 1525: -118.3919,
 1526: -118.3842,
 1527: -118.3734,
 1529: -118.3659,
 1531: -118.4093,
 1532: -118.4016,
 1533: -118.3953,
 1535: -118.3823,
 1537: -118.3616,
 1538: -118.3749,
 1539: -118.3646,
 1541: -118.4081,
 1542: -118.3784,
 1543: -118.4008,
 1544: -118.4002,
 1545: -118.3931,
 1546: -118.3852,
 1547: -118.3814,
 1548: -118.372,
 1549: -118.3723,
 1551: -118.3998,
 1553: -118.3911,
 1555: -118.3741,
 1557: -118.3667,
 1559: -118.3569,
 1562: -118.4074,
 1563: -118.3869,
 1565: -118.3768,
 1566: -118.3689,
 1567: -118.3637,
 1569: -118.356,
 1581: -118.4067,
 1583: -118.389,
 1585: -118.3714,
 1586: -118.3626,
 1587: -118.3591,
 1588: -118.3451,
 1589: -118.3411,
 1591: -118.4013,
 1595: -118.3888,
 1596: -118.3713,
 1599: -118.3561,
 1601: -118.4161,
 1602: -118.4076,
 1603: -118.3973,
 1605: -118.3923,
 1606: -118.3805,
 1608: -118.3581,
 1611: -118.4252,
 1612: -118.4208,
 1613: -118.406,
 1614: -118.4004,
 1615: -118.3905,
 1617: -118.321,
 1618: -118.3072,
 1619: -118.2908,
 1621: -118.4342,
 1622: -118.43,
 1623: -118.4156,
 1633: -118.3996,
 1634: -118.3912,
 1635: -118.3622,
 1636: -118.3348,
 1637: -118.3072,
 1638: -118.2936,
 1639: -118.2826,
 1641: -118.4272,
 1642: -118.4222,
 1643: -118.4192,
 1645: -118.4082,
 1651: -118.418,
 1653: -118.4107,
 1654: -118.4011,
 1655: -118.36,
 1656: -118.3146,
 1657: -118.2902,
 1658: -118.2817,
 1659: -118.2715,
 1661: -118.4115,
 1663: -118.3992,
 1664: -118.3884,
 1665: -118.3772,
 1666: -118.4415,
 1667: -118.3579,
 1668: -118.2889,
 1669: -118.2703,
 1671: -118.3908,
 1672: -118.3904,
 1673: -118.3838,
 1675: -118.3709,
 1676: -118.3643,
 1677: -118.3501,
 1678: -118.3502,
 1679: -118.2947,
 1681: -118.4015,
 1682: -118.3959,
 1683: -118.4072,
 1684: -118.3916,
 1685: -118.3846,
 1687: -118.3717,
 1689: -118.3697,
 1691: -118.4024,
 1693: -118.4019,
 1695: -118.371,
 1698: -118.3585,
 1699: -118.3492,
 1701: -118.5721,
 1703: -118.5459,
 1705: -118.509,
 1707: -118.5082,
 1708: -118.494,
 1709: -118.4717,
 1712: -118.554,
 1713: -118.5411,
 1714: -118.5383,
 1715: -118.5209,
 1716: -118.5064,
 1717: -118.4911,
 1718: -118.4779,
 1719: -118.4715,
 1721: -118.6073,
 1722: -118.6014,
 1723: -118.5847,
 1725: -118.5626,
 1727: -118.5492,
 1728: -118.5341,
 1729: -118.5134,
 1732: -118.4555,
 1735: -118.5154,
 1737: -118.4976,
 1738: -118.4787,
 1739: -118.4828,
 1743: -118.5349,
 1745: -118.5175,
 1747: -118.4977,
 1749: -118.4813,
 1751: -118.6045,
 1752: -118.5913,
 1753: -118.5786,
 1754: -118.5363,
 1755: -118.5277,
 1756: -118.5136,
 1757: -118.4978,
 1758: -118.4858,
 1759: -118.4771,
 1761: -118.6052,
 1762: -118.5843,
 1763: -118.5653,
 1764: -118.5587,
 1765: -118.5483,
 1766: -118.5457,
 1767: -118.5362,
 1768: -118.5124,
 1771: -118.5822,
 1772: -118.5679,
 1773: -118.5292,
 1774: -118.5234,
 1775: -118.5102,
 1776: -118.4978,
 1777: -118.4895,
 1778: -118.4825,
 1779: -118.4778,
 1781: -118.5856,
 1782: -118.5619,
 1783: -118.5514,
 1784: -118.5405,
 1785: -118.5363,
 1787: -118.5223,
 1788: -118.5099,
 1791: -118.5834,
 1792: -118.5623,
 1793: -118.5503,
 1794: -118.5363,
 1795: -118.5158,
 1796: -118.5005,
 1797: -118.4897,
 1798: -118.4791,
 1799: -118.4796,
 1801: -118.2871,
 1802: -118.2772,
 1803: -118.2694,
 1804: -118.2606,
 1805: -118.2689,
 1806: -118.2605,
 1821: -118.287,
 1822: -118.277,
 1823: -118.2688,
 1824: -118.2601,
 1826: -118.2463,
 1827: -118.2397,
 1829: -118.2327,
 1831: -118.2859,
 1832: -118.2768,
 1834: -118.2631,
 1835: -118.2526,
 1836: -118.2507,
 1837: -118.2431,
 1838: -118.237,
 1839: -118.2317,
 1841: -118.2876,
 1842: -118.2763,
 1844: -118.2632,
 1846: -118.2507,
 1849: -118.2348,
 1851: -118.2874,
 1861: -118.2874,
 1862: -118.2756,
 1863: -118.2664,
 1864: -118.2579,
 1871: -118.2879,
 1881: -118.2876,
 ...}

Test on the null table:

In [256]:
df_ll_nulls.loc[df_ll_nulls['lat'] == 0, 'lat'] = df_ll_nulls['rpt_dist_no'].map(lat_impute_dict)
df_ll_nulls.loc[df_ll_nulls['lon'] == 0, 'lon'] = df_ll_nulls['rpt_dist_no'].map(lon_impute_dict)

df_ll_nulls.head()

,area,rpt_dist_no,location,premis_cd,premis_desc,lat,lon
120,6,639,5400 HOLLYWOOD BL,203.0,OTHER BUSINESS,34.1034,-118.3051
297,6,636,SUNSET,101.0,STREET,34.1027,-118.3331
542,6,659,1300 N HARVARD BL,502.0,"MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)",34.0969,-118.3044
805,6,639,HOLLYWOOD,102.0,SIDEWALK,34.1034,-118.3051
892,19,1998,7800 VAN NUYS BL,101.0,STREET,34.2158,-118.4418

Print the first few lat-lon values to ensure they're left unchanged:

In [257]:
df[['lat', 'lon']].head(3)

       lat       lon
0  33.9737 -118.2827
1  34.2467 -118.4479
2  34.0463 -118.4171

In [258]:
print(f'non-zero values from table before imputation:')
df[['lat', 'lon']].head(3)

non-zero values from table before imputation:

       lat       lon
0  33.9737 -118.2827
1  34.2467 -118.4479
2  34.0463 -118.4171

In [259]:
# Impute values for 'lat' and 'lon' columns where they are 0
df.loc[df['lat'] == 0, 'lat'] = df['rpt_dist_no'].map(lat_impute_dict)
df.loc[df['lon'] == 0, 'lon'] = df['rpt_dist_no'].map(lon_impute_dict)

# Confirm initial lat-lon values remain unchanged
print('non-zeros remain unchanged:')
df[['lat', 'lon']].head(3)

non-zeros remain unchanged:

       lat       lon
0  33.9737 -118.2827
1  34.2467 -118.4479
2  34.0463 -118.4171

In [260]:
# Confirm there are no more zero geolocation values in 'lat' or 'lon'
df[df['lat'] ==0][['lat', 'lon']].sum()

lat    0.0
lon    0.0
dtype: float64

In [279]:
# Quantize missing values:
df[['lat', 'lon']].isna().sum()

lat    3
lon    3
dtype: int64

That nearly fixed all the records.  These 3 most likely had `rpt_dist_no` values not represented in the remaining complete record values.  We'll just impute the remaining 3 with less regionally specific averages using the 21 `area` values instead:

In [280]:
# Create a dictionary to key area to mean lat:
area_lat = df_ll_complete[['area', 'lat']].groupby(['area']).agg(['mean']).round(4).to_dict()
area_lat = area_lat[('lat', 'mean')]

# Create a dictionary to key area to mean lon:
area_lon = df_ll_complete[['area', 'lon']].groupby(['area']).agg(['mean']).round(4).to_dict()
area_lon = area_lon[('lon', 'mean')]

# Impute the remaining 3 changes:
df.loc[df['lat'].isna(), 'lat'] = df['area'].map(area_lat)
df.loc[df['lon'].isna(), 'lon'] = df['area'].map(area_lon)

In [281]:
# Check again for nulls:
df[['lat', 'lon']].isna().sum()

lat    0
lon    0
dtype: int64

In [ ]:
#dropping irrelevant columns for visuals
df_vis = df.drop(['area_name', 'location', 'cross_street'], axis=1)

df_vis.to_csv('./data/df_vis.csv', index=False)
df_vis

,dr_no,date_rptd,date_occ,time_occ,area,area_name,rpt_dist_no,crm_cd,crm_cd_desc,vict_age,...,premis_cd,premis_desc,weapon_used_cd,weapon_desc,status_desc,crm_cd_1,crm_cd_2,crm_cd_3,lat,lon
0,201223780,2020-11-02,11/02/2020 12:00:00 AM,11:20:00,12,77th Street,1256,210,ROBBERY,65,...,102.0,SIDEWALK,204.0,FOLDING KNIFE,Invest Cont,210.0,NaN,NaN,33.9737,-118.2827
1,201911283,2020-06-23,06/23/2020 12:00:00 AM,03:15:00,19,Mission,1958,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",51,...,210.0,RESTAURANT/FAST FOOD,NaN,NaN,Invest Cont,740.0,998.0,NaN,34.2467,-118.4479
2,200806654,2020-02-28,02/28/2020 12:00:00 AM,15:45:00,8,West LA,885,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),38,...,108.0,PARKING LOT,NaN,NaN,Invest Cont,420.0,NaN,NaN,34.0463,-118.4171
3,220912167,2022-08-03,07/26/2022 12:00:00 AM,17:30:00,9,Van Nuys,955,901,VIOLATION OF RESTRAINING ORDER,64,...,502.0,"MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)",NaN,NaN,Adult Other,901.0,NaN,NaN,34.1668,-118.4445
4,200817110,2020-12-02,11/27/2020 12:00:00 AM,15:00:00,8,West LA,802,662,"BUNCO, GRAND THEFT",73,...,501.0,SINGLE FAMILY DWELLING,NaN,NaN,Invest Cont,662.0,NaN,NaN,34.0889,-118.5325
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
400141,201115779,2020-11-16,11/11/2020 12:00:00 AM,12:00:00,11,Northeast,1138,420,THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER),0,...,101.0,STREET,NaN,NaN,Invest Cont,420.0,NaN,NaN,34.1152,-118.1898
400142,222013649,2022-06-24,06/23/2022 12:00:00 AM,19:00:00,20,Olympic,2039,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",27,...,122.0,"VEHICLE, PASSENGER/TRUCK",NaN,NaN,Invest Cont,740.0,NaN,NaN,34.0598,-118.2891
400143,221817476,2022-09-16,09/16/2022 12:00:00 AM,06:30:00,18,Southeast,1801,220,ATTEMPTED ROBBERY,37,...,101.0,STREET,500.0,UNKNOWN WEAPON/OTHER WEAPON,Invest Cont,220.0,998.0,NaN,33.9580,-118.2894
400144,201510806,2020-05-27,05/22/2020 12:00:00 AM,16:00:00,15,N Hollywood,1519,903,CONTEMPT OF COURT,34,...,502.0,"MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)",NaN,NaN,Adult Other,903.0,NaN,NaN,34.1922,-118.3660
400145,201214091,2020-06-04,06/03/2020 12:00:00 AM,01:30:00,12,77th Street,1248,510,VEHICLE - STOLEN,0,...,101.0,STREET,NaN,NaN,Invest Cont,510.0,NaN,NaN,33.9819,-118.2870

:

In [ ]:
df
['dr_no', 'date_rptd', 'date_occ', 'time_occ', 'area', 'area_name', 'rpt_dist_no', 'crm_cd', 'crm_cd_desc', 'vict_age', 'vict_sex', 'vict_descent', 'premis_cd', 'premis_desc', 'weapon_used_cd', 'weapon_desc', 'status_desc', 'crm_cd_1', 'crm_cd_2', 'crm_cd_3', 'crm_cd_4', 'location', 'cross_street', 'lat', 'lon']

Index(['dr_no', 'date_rptd', 'date_occ', 'time_occ', 'area', 'area_name',
       'rpt_dist_no', 'crm_cd', 'crm_cd_desc', 'vict_age', 'vict_sex',
       'vict_descent', 'premis_cd', 'premis_desc', 'weapon_used_cd',
       'weapon_desc', 'status_desc', 'crm_cd_1', 'crm_cd_2', 'crm_cd_3',
       'crm_cd_4', 'location', 'cross_street', 'lat', 'lon'],
      dtype='object')

:

Does the time difference between date of crime reported and date the crime occurred display variances between geographic locations?

In [ ]:
'dr_no', 'date_rptd', 'date_occ'

:

does this time gap vary between crime types?

:

does this time gap vary between crime victim types?

:

does this time gap vary between crime types victim ages?

:

Does the crime rate and severity differ between the 21 LAPD community police stations?

:

Does the severity of crimes differ between the stations?

:

Can you generate a map with different sizes and different coloured bubbles for different crime types?

:

Is there a way to determine weather some crimes actually happen less frequently in certain areas, or rather might just be less frequently reported?

:

Are there any correlations between weapons used and victim type?

:

How about crime type? Geography?

:

Do the types of weapons used change over time?

:

Are weapons being used with increased or decreased frequency?

: